name: NuGet Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.100'  

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release

    - name: Publish
      if: success()
      run: |
        dotnet nuget push \
        ./ExplodingWhale/ExplodingWhale.Package/bin/Release/ExplodingWhale*.nupkg \
        --source "https://api.nuget.org/v3/index.json" \
        --api-key ${{ secrets.NUGET_API_KEY }}